### ISSUE TITLE
License Expire, Container Restarting

### ISSUE THREAD

**Issue by ikac5** [litespeedtech/lsws-magento-docker-env#1]
After License Expired, the Litespeed container can't be up and always restarting in loop,.
How to enter new license, when container is not up, and is not exist litespeed service ?

**Comment by Code-Egg** [comment]
For this case, you will need to put the serial number file in the lsws folder, then send a register command.

### Add a serial number 
In the host server, access to the **lsws-magento-docker-env > lsws > conf** folder. 
```
sudo echo 'YOUR_SERIAL' > serial.no
```

### Run the register command
```
docker exec -it LITESPEED_CONTAINER_ID su -c '/usr/local/lsws/bin/lshttpd -r'
```
You might need to run this several times since the container keeps restarting. 
If successful, you should see output like this 
```
2021-08-04  [NOTICE] Memory size is: 4039600KB.
2021-08-04  [NOTICE] [OK] Updated license key has been created at /usr/local/lsws/conf/license.key.
```

Next time, you could use this method to apply for new license easily before the license expires. 
https://github.com/litespeedtech/lsws-magento-docker-env#applying-license-to-lsws

Let me know if it works.

**Comment by ikac5** [comment]
After multiple tries I succeeded. Thanks

**Comment by Code-Egg** [comment]
Glad to know it works
